name: Beta Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Code checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: npm

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: |
          composer install -q --no-dev --optimize-autoloader --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci

      - name: Build
        run: npm run build

      - name: Create release branch and bump version
        run: sed -i "s/    'version' => 'development',/    'version' => 'beta',/" config/app.php

      - name: Add commit sha to app.php
        run: sed -i "s/    'commit' => '',/    'commit' => '${{ github.sha }}',/" config/app.php

      - name: Create beta archive
        run: | 
            rm -rf node_modules tests CODE_OF_CONDUCT.md CONTRIBUTING.md flake.lock flake.nix phpstan.neon phpunit.xml shell.nix
            tar -czf paymenter.tar.gz * .env.example .gitignore
    
      - name: Move file to seperate directory for r2 upload
        run: |
          mkdir -p r2_upload
          cp paymenter.tar.gz r2_upload/

      # Upload artifact
      - name: Upload archive
        uses: ryand56/r2-upload-action@b801a390acbdeb034c5e684ff5e1361c06639e7c # v1.4
        with:
          r2-account-id: ${{ secrets.CF_R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.CF_R2_KEY_ID }}
          r2-secret-access-key: ${{ secrets.CF_R2_KEY_ACCESS }}
          r2-bucket: paymenter-api
          source-dir: r2_upload
          destination-dir: ./
